#!/bin/bash

setup (){
    #chang your database password here.
    yourPW=''

    sudo apt-get -y install vim
    sudo apt-get -y install rar unrar
    sudo apt-get -y install git
    sudo apt-get -y install python3  python3-pip
    sudo apt-get -y install openssh-server openssh-client

    #start to install mysql
    sudo debconf-set-selections <<< 'MySQL-server mysql-server/root_password password '$yourPW''
    sudo debconf-set-selections <<< 'MySQL-server mysql-server/root_password_again password '$yourPW''
    sudo apt-get -y install mysql-server mysql-client

    #start to install php and apache2
    sudo apt-get -y install apache2 
    sudo apt-get -y install php5 libapache2-mod-php php-mysql
    sudo sh -c 'echo "<?php\nphpinfo()\n?>" >> /var/www/html/info.php'
    sudo /etc/init.d/apache2 restart

    # edit /etc/php/7.0/apache2/php.ini ,delete ';' in lines "extension=php_mysqli.dll" ans "extension=php_pdo_mysql.dll". This 
    # action will make php support mysql.


    #change sources to tsinghua's
    sudo rm -f /etc/apt/sources.list
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates universe" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial multiverse" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates multiverse" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security universe" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security multiverse" >> /etc/apt/sources.list'

    # change hosts
    sudo rm -f /etc/hosts
    sudo mv hosts /etc/hosts

    echo -e "All installations Over!!\n" 
    echo -e "Use /etc/init.d/apache2 start/stop/restart to manage apache2 service."
    echo -e "Use /etc/init.d/mysql start/stop/restart to manage database service.\nAnd,the administrator password would be $yourPW ."
}


if [ $yourPW = '' ]
then
    echo "Please set up your password in this file."
else
    echo "Your password is $yourPW."
    echo "Start installing......"
    setup
fi


#libapache2-mod-php php-mysql /service mysql restart/  /service apache2 restart/
# theme : https://github.com/anmoljagetia/Flatabulous
# zsh http://yijiebuyi.com/blog/b9b5e1ebb719f22475c38c4819ab8151.html
# shadowsocks :https://github.com/shadowsocks/shadowsocks-qt5/wiki/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97
# apt-get remove fcitx-qimpannl

# removed gnome-software
#   sudo apt purge gnome-software
# To add the old one back run
#   sudo apt install software-center

# indicator-sysmonitor ppa:
#   sudo add-apt-repository ppa:fossfreedom/indicator-sysmonitor 

# code blocks
#   sudo add-apt-repository ppa:damien-moore/codeblocks-stable  
#   sudo apt-get install codeblocks codeblocks-contrib

## SSH RSA 
# ssh-keygen -t rsa -C "f20140807@outlook.com"

