#!/bin/bash

setup (){
    #chang your database password here.
    yourPW='dhn78834'

    sudo apt-get -y install vim
    sudo apt-get -y install rar unrar
    sudo apt-get -y install git
    sudo apt-get -y install Python3
    sudo apt-get -y install openssh-server openssh-client

    #start to install mysql
    sudo debconf-set-selections <<< 'MySQL-server mysql-server/root_password password '$yourPW''
    sudo debconf-set-selections <<< 'MySQL-server mysql-server/root_password_again password '$yourPW''
    sudo apt-get -y install mysql-server mysql-client

    #start to install php and apache2
    sudo apt-get -y install apache2 libapache2-mod-auth-mysql
    sudo apt-get -y install php5 libapache2-mod-php5
    sudo apt-get -y install php5-mysql php5-curl php5-gd php5-idn php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl
    sudo echo "<?php\nphpinfo()\n?>" > /var/www/html/info.php
    sudo /etc/init.d/apache2 restart

    #change sources to tsinghua's
    sudo rm -f /etc/apt/sources.list
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates universe" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial multiverse" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates multiverse" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security universe" >> /etc/apt/sources.list'
    sudo sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security multiverse" >> /etc/apt/sources.list'

    # change hosts
    git clone https://github.com/DongFrancis/own_setup.git own_setup
    sudo rm -f /etc/hosts
    sudo mv own_setup/hosts /etc/hosts

    echo -e "All installations Over!!\n" 
    echo -e "Use /etc/init.d/apache2 start/stop/restart to manage apache2 service."
    echo -e "Use /etc/init.d/mysql start/stop/restart to manage database service.\nAnd,the administrator password would be $yourPW ."
}


if [ $yourPW = '' ]
then
    echo "Please set up your password in this file."
else
    echo "Your password is $yourPW.\nStart installing......"
    setup
fi
